#!/usr/bin/env bash
# One command: start the local bridge server + open Firefox with the Copilot
# CLI Bridge extension loaded.
#
# Firefox is the only browser this can work in — Chrome and Edge refuse to let
# any extension script copilot.microsoft.com ("the extensions gallery cannot be
# scripted"), so the content script never runs there.
#
# Usage:
#   ./launch-firefox-bridge.sh            start server (if needed) + Firefox
#   ./launch-firefox-bridge.sh --server   just the server, in the foreground
#   ./launch-firefox-bridge.sh --restart  restart the server, then Firefox
#
# Ctrl+C stops Firefox; the server keeps running (stop it with --stop).

set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT="${BRIDGE_PORT:-8765}"
STATE="$HOME/.copilot-cli-bridge"
mkdir -p "$STATE"

# ---- resolve node --------------------------------------------------------
# A GUI-launched shell (or an nvm lazy-loader) often doesn't have node on PATH.
find_node() {
  if command -v node >/dev/null 2>&1 && node --version >/dev/null 2>&1; then
    command -v node; return
  fi
  for c in /usr/local/bin/node /opt/homebrew/bin/node "$HOME/.local/bin/node"; do
    [ -x "$c" ] && { echo "$c"; return; }
  done
  # Newest nvm install, if there is one.
  local nvm_node
  nvm_node="$(ls -d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -V | tail -1 || true)"
  [ -n "$nvm_node" ] && { echo "$nvm_node"; return; }
  return 1
}

NODE_BIN="$(find_node)" || { echo "error: node not found. Install Node.js and retry." >&2; exit 1; }
export PATH="$(dirname "$NODE_BIN"):$PATH"

# ---- token ---------------------------------------------------------------
TOKEN_FILE="$DIR/.bridge-token"
if [ ! -s "$TOKEN_FILE" ]; then
  echo "Generating a new bridge token ..."
  "$NODE_BIN" -e 'process.stdout.write(require("crypto").randomBytes(24).toString("hex"))' > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
fi
TOKEN="$(cat "$TOKEN_FILE")"

# The extension can't read files, so bake the token into a generated script
# that the background page loads before background.js.
cat > "$DIR/firefox-extension/token.js" <<EOF
// Generated by launch-firefox-bridge.sh — do not edit, do not commit.
const BRIDGE_TOKEN = "$TOKEN";
EOF

# ---- server --------------------------------------------------------------
server_up() {
  curl -sf -m 2 -H "X-Bridge-Token: $TOKEN" "http://127.0.0.1:$PORT/ping" >/dev/null 2>&1
}

stop_server() {
  pkill -f "bridge-server.js" 2>/dev/null || true
  pkill -f "local-server.js" 2>/dev/null || true
  sleep 1
}

start_server() {
  echo "Starting bridge server on 127.0.0.1:$PORT ..."
  nohup "$NODE_BIN" "$DIR/server/bridge-server.js" >"$STATE/server.log" 2>&1 &
  for _ in $(seq 1 25); do
    sleep 0.2
    server_up && return 0
  done
  echo "error: server did not come up. Last lines of $STATE/server.log:" >&2
  tail -20 "$STATE/server.log" >&2
  return 1
}

case "${1:-}" in
  --stop)
    stop_server
    echo "Bridge server stopped."
    exit 0
    ;;
  --server)
    stop_server
    echo "Bridge server (foreground). Ctrl+C to stop."
    exec "$NODE_BIN" "$DIR/server/bridge-server.js"
    ;;
  --restart)
    stop_server
    ;;
esac

# The old local-server.js only understands /run; make sure it isn't the one
# holding the port.
if server_up; then
  VERSION="$(curl -sf -m 2 -H "X-Bridge-Token: $TOKEN" "http://127.0.0.1:$PORT/ping" | sed -n 's/.*"version":"\([^"]*\)".*/\1/p')"
  case "$VERSION" in
    2.*) echo "Bridge server already running (v$VERSION)." ;;
    *)   echo "Replacing old bridge server (v${VERSION:-unknown}) ..."; stop_server; start_server ;;
  esac
else
  lsof -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1 && {
    echo "Port $PORT is busy but not answering our token — stopping it."; stop_server; }
  start_server
fi

# ---- firefox -------------------------------------------------------------
FF="/Applications/Firefox.app/Contents/MacOS/firefox"
[ -x "$FF" ] || FF="$(command -v firefox || true)"
[ -n "$FF" ] && [ -x "$FF" ] || { echo "error: Firefox not found at /Applications/Firefox.app" >&2; exit 1; }

PROFILE="$STATE/firefox-profile"
mkdir -p "$PROFILE"

echo "Launching Firefox with the Copilot CLI Bridge extension ..."
echo "In the chat box, type !help to see what it can do."
exec npx --yes web-ext run \
  --source-dir="$DIR/firefox-extension" \
  --firefox="$FF" \
  --firefox-profile="$PROFILE" \
  --keep-profile-changes \
  --profile-create-if-missing \
  --start-url="https://copilot.microsoft.com" \
  --no-input
