#!/usr/bin/env bash
# One command: start the local bridge server + open Firefox with the Copilot
# CLI Bridge extension loaded.
#
# Firefox is the only browser this can work in — Chrome and Edge refuse to let
# any extension script copilot.microsoft.com ("the extensions gallery cannot be
# scripted"), so the content script never runs there.
#
# Usage:
#   ./launch-firefox-bridge.sh            start server (if needed) + Firefox
#   ./launch-firefox-bridge.sh --server   just the server, in the foreground
#   ./launch-firefox-bridge.sh --restart  restart the server, then Firefox
#   ./launch-firefox-bridge.sh --manual   start the server and tell you how to
#                                         load the extension by hand (no npm)
#
# Ctrl+C stops Firefox; the server keeps running (stop it with --stop).

set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE="$HOME/.copilot-cli-bridge"
mkdir -p "$STATE"

# Port: 18765 by default. If it's taken by something else we walk forward and
# use the first free one, then tell the extension which port we landed on — so
# a machine that already runs something on our default needs no edits. Setting
# BRIDGE_PORT explicitly pins it and disables the search.
DEFAULT_PORT=18765
PORT="${BRIDGE_PORT:-$DEFAULT_PORT}"
PORT_PINNED="${BRIDGE_PORT:+yes}"

# ---- resolve node --------------------------------------------------------
# A GUI-launched shell (or an nvm lazy-loader) often doesn't have node on PATH.
find_node() {
  if command -v node >/dev/null 2>&1 && node --version >/dev/null 2>&1; then
    command -v node; return
  fi
  for c in /usr/local/bin/node /opt/homebrew/bin/node "$HOME/.local/bin/node"; do
    [ -x "$c" ] && { echo "$c"; return; }
  done
  # Newest nvm install, if there is one.
  local nvm_node
  nvm_node="$(ls -d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -V | tail -1 || true)"
  [ -n "$nvm_node" ] && { echo "$nvm_node"; return; }
  return 1
}

NODE_BIN="$(find_node)" || { echo "error: node not found. Install Node.js and retry." >&2; exit 1; }
export PATH="$(dirname "$NODE_BIN"):$PATH"

# ---- token ---------------------------------------------------------------
TOKEN_FILE="$DIR/.bridge-token"
if [ ! -s "$TOKEN_FILE" ]; then
  echo "Generating a new bridge token ..."
  "$NODE_BIN" -e 'process.stdout.write(require("crypto").randomBytes(24).toString("hex"))' > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
fi
TOKEN="$(cat "$TOKEN_FILE")"

# ---- server --------------------------------------------------------------
port_busy() {
  lsof -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
}

# True only if *our* bridge answers there. Checking the status code isn't
# enough — plenty of dev servers return 200 for an unknown path — so we look
# for the service marker in the body.
ping_body() {
  curl -sf -m 2 -H "X-Bridge-Token: $TOKEN" "http://127.0.0.1:$1/ping" 2>/dev/null
}

ours_on() {
  ping_body "$1" | grep -q '"service":"copilot-cli-bridge"'
}

stop_server() {
  pkill -f "bridge-server.js" 2>/dev/null || true
  pkill -f "local-server.js" 2>/dev/null || true
  sleep 1
}

# Settle on a port: adopt ours if it's already up, otherwise take the first
# free one from $PORT upward. Sets PORT and ADOPTED.
choose_port() {
  local p="$PORT" tries=0
  while [ "$tries" -lt 50 ]; do
    if ours_on "$p"; then PORT="$p"; ADOPTED=yes; return 0; fi
    if ! port_busy "$p"; then PORT="$p"; ADOPTED=no; return 0; fi
    if [ -n "$PORT_PINNED" ]; then
      echo "error: BRIDGE_PORT=$p is held by something else. Free it, or pin a different port." >&2
      return 1
    fi
    echo "Port $p is taken by something else; trying $((p + 1)) ..."
    p=$((p + 1))
    tries=$((tries + 1))
  done
  echo "error: no free port found from $PORT upward." >&2
  return 1
}

start_server() {
  echo "Starting bridge server on 127.0.0.1:$PORT ..."
  BRIDGE_PORT="$PORT" nohup "$NODE_BIN" "$DIR/server/bridge-server.js" >"$STATE/server.log" 2>&1 &
  for _ in $(seq 1 25); do
    sleep 0.2
    ours_on "$PORT" && return 0
  done
  echo "error: server did not come up. Last lines of $STATE/server.log:" >&2
  tail -20 "$STATE/server.log" >&2
  return 1
}

# The extension can't read files, so bake the token *and the port we settled
# on* into a generated script the background page loads before background.js.
write_config() {
  cat > "$DIR/firefox-extension/bridge-config.js" <<EOF
// Generated by launch-firefox-bridge.sh — do not edit, do not commit.
const BRIDGE_TOKEN = "$TOKEN";
const BRIDGE_PORT = $PORT;
EOF
}

case "${1:-}" in
  --stop)
    stop_server
    echo "Bridge server stopped."
    exit 0
    ;;
  --server)
    stop_server
    choose_port || exit 1
    write_config
    echo "Bridge server on 127.0.0.1:$PORT (foreground). Ctrl+C to stop."
    exec env BRIDGE_PORT="$PORT" "$NODE_BIN" "$DIR/server/bridge-server.js"
    ;;
  --restart)
    stop_server
    ;;
  --manual)
    # Start the server, then print how to side-load the extension by hand.
    MANUAL_LOAD=yes
    ;;
esac

choose_port || exit 1

if [ "$ADOPTED" = yes ]; then
  # An older build only understands /run; replace it rather than talk to it.
  VERSION="$(curl -sf -m 2 -H "X-Bridge-Token: $TOKEN" "http://127.0.0.1:$PORT/ping" \
             | sed -n 's/.*"version":"\([^"]*\)".*/\1/p')"
  case "$VERSION" in
    2.*) echo "Bridge server already running on $PORT (v$VERSION)." ;;
    *)   echo "Replacing old bridge server (v${VERSION:-unknown}) ..."
         stop_server
         choose_port || exit 1
         start_server || exit 1 ;;
  esac
else
  start_server || exit 1
fi

write_config

# ---- firefox -------------------------------------------------------------
FF="/Applications/Firefox.app/Contents/MacOS/firefox"
[ -x "$FF" ] || FF="$(command -v firefox || true)"
[ -n "$FF" ] && [ -x "$FF" ] || { echo "error: Firefox not found at /Applications/Firefox.app" >&2; exit 1; }

PROFILE="$STATE/firefox-profile"
mkdir -p "$PROFILE"

manual_instructions() {
  cat <<EOM

Load the extension by hand — this needs no npm and no web-ext:

  1. In Firefox, open:   about:debugging#/runtime/this-firefox
  2. Click:              Load Temporary Add-on…
  3. Choose this file:   $DIR/firefox-extension/manifest.json
  4. Open https://copilot.microsoft.com and type !help in the chat box.

The bridge server is running on 127.0.0.1:$PORT and stays up after this
script exits. Firefox forgets temporary add-ons when it restarts, so repeat
steps 1-3 after a Firefox restart.
EOM
}

if [ "${MANUAL_LOAD:-}" = yes ]; then
  echo "Bridge server ready on 127.0.0.1:$PORT."
  manual_instructions
  exit 0
fi

# Prefer a web-ext that is already on disk. `npx --yes` reaches out to the
# registry, which fails on a locked-down network — and it only ever worked
# here because an earlier run left one in the npx cache.
find_web_ext() {
  command -v web-ext >/dev/null 2>&1 && { command -v web-ext; return 0; }
  local c
  for c in \
    "$DIR/node_modules/.bin/web-ext" \
    "$(dirname "$NODE_BIN")/web-ext" \
    "$HOME/.npm-global/bin/web-ext" \
    /usr/local/bin/web-ext \
    /opt/homebrew/bin/web-ext; do
    [ -x "$c" ] && { echo "$c"; return 0; }
  done
  c="$(ls -d "$HOME"/.npm/_npx/*/node_modules/.bin/web-ext 2>/dev/null | head -1 || true)"
  [ -n "$c" ] && [ -x "$c" ] && { echo "$c"; return 0; }
  return 1
}

WEB_EXT="$(find_web_ext || true)"

# macOS has no `timeout(1)`, and npm against an unreachable or hostile registry
# can sit there for a very long time. Cap it so the launcher never hangs.
run_bounded() {
  local secs="$1"; shift
  "$@" &
  local pid=$! i=0
  while kill -0 "$pid" 2>/dev/null; do
    if [ "$i" -ge "$secs" ]; then
      kill -TERM "$pid" 2>/dev/null
      sleep 1
      kill -KILL "$pid" 2>/dev/null
      return 124
    fi
    sleep 1
    i=$((i + 1))
  done
  wait "$pid"
}

if [ -z "$WEB_EXT" ]; then
  NPM_BIN="$(dirname "$NODE_BIN")/npm"
  [ -x "$NPM_BIN" ] || NPM_BIN="$(command -v npm || true)"
  echo "web-ext isn't installed. Installing it into $DIR/node_modules ..."
  echo "(this uses whatever registry your .npmrc points at; up to 3 minutes)"
  if [ -n "$NPM_BIN" ]; then
    run_bounded 180 "$NPM_BIN" install --no-save --no-audit --no-fund \
      --fetch-retries=1 --fetch-timeout=30000 \
      --prefix "$DIR" web-ext >"$STATE/web-ext-install.log" 2>&1
    case $? in
      0) WEB_EXT="$(find_web_ext || true)" ;;
      124) echo "npm timed out after 3 minutes." | tee -a "$STATE/web-ext-install.log" >&2 ;;
    esac
  else
    echo "npm not found on PATH." > "$STATE/web-ext-install.log"
  fi
fi

if [ -z "$WEB_EXT" ]; then
  echo
  echo "Could not install web-ext. Last lines of $STATE/web-ext-install.log:" >&2
  tail -12 "$STATE/web-ext-install.log" 2>/dev/null >&2 || true
  cat >&2 <<'EOM'

If npm reported 403, it is talking to registry.npmjs.org instead of your
corporate registry. npm reads that from .npmrc — not from ~/.ssh, which only
applies to git-protocol dependencies:

  npm config set registry https://<your-registry-host>/api/npm/npm/
  npm login --registry https://<your-registry-host>/api/npm/npm/

Then re-run this script. You do not need web-ext at all, though:
EOM
  manual_instructions
  echo "The server is up; loading the extension by hand is all that's left." >&2
  exit 1
fi

echo "Launching Firefox with the Copilot CLI Bridge extension ..."
echo "(web-ext: $WEB_EXT)"
echo "In the chat box, type !help to see what it can do."
exec "$WEB_EXT" run \
  --source-dir="$DIR/firefox-extension" \
  --firefox="$FF" \
  --firefox-profile="$PROFILE" \
  --keep-profile-changes \
  --profile-create-if-missing \
  --start-url="https://copilot.microsoft.com" \
  --no-input
